`define ALU_ADD 0
`define ALU_SUB	1
`define ALU_LSR	2
`define ALU_LSL	3
`define ALU_RSR	4
`define ALU_RSL	5
`define ALU_MUL	6
`define ALU_DIV	7
`define ALU_MOD	8
`define ALU_AND	9
`define ALU_OR	10
`define ALU_XOR	11
`define ALU_CMP	12
`define ALU_TST	13
`define ALU_NOT	14
`define ALU_INC	15
`define ALU_DEC	16
`define ALU_NOP 17